---
Title: "Mini Project III - Financial Data Distribution"
Author: "Jabes Gallardo"
Date: "6/8/2021"
Output: pdf_document
---

---
Importing and Cleaning Data from CRSP-COMPUSTAT: MKVALT Test Set
---

```{Importing MKVALT - Test Set}
#Expected final output approximately 34.02%
library(readxl)
CRSP_COMPUSTAT_Data <- read_excel("Desktop/Rice REU/Financial Data Distribution/CRSP-COMPUSTAT Data.xlsx", 
    sheet = "MKVALT", col_types = c("numeric", 
        "numeric"))
view(CRSP_COMPUSTAT_Data)

```

```{Creating and Subsetting Data Frame}
MCRCOMP <- data.frame(CRSP_COMPUSTAT_Data)
view(MCRCOMP)

for (i in c(0, 1, 3)){
  MCRCOMP <- subset(MCRCOMP, MCRCOMP$Stock.Exchange.Code != i)
  MCRCOMP_C <- MCRCOMP
}

```

```{Coverage Function}
cov <- function(vector){
  length(na.omit(vector))/length(vector)
}

```

```{Calculating Coverage for MKVALT}
MCRCOMP_CI <- as.data.frame(MCRCOMP_C[,2])

MCRCOMP_CIF <- sapply(MCRCOMP_CI, cov)
MCRCOMP_CIF
#ouput is 0.3808714, which is close to 34.02%

```

---
Importing and Cleaning Data from CRSP-COMPUSTAT: Full Set
---

```{Importing Libraries}
library(tidyverse)
library(tidyquant)
library(ggplot2)
library(readxl)
library(stringr)
library(gridExtra)

```

```{Importing Excel Table}
CRSP_COMPUSTAT_Data <- read_excel("Desktop/Rice REU/Financial Data Distribution/CRSP-COMPUSTAT Data.xlsx", 
    col_types = c("text", "date", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "numeric", "numeric", 
        "numeric", "text", "numeric"))
View(CRSP_COMPUSTAT_Data)

```

```{Creating Useful Functions}
#Coverage Function
cov <- function(vector){
  round((length(na.omit(vector))/length(vector))*100, digits = 2)
}

```

```{Creating and Subsetting Data Frame}
CRCOMP <- data.frame(CRSP_COMPUSTAT_Data)
view(CRCOMP)

for (i in c(0, 1, 3)){
  CRCOMP <- subset(CRCOMP, CRCOMP$Stock.Exchange.Code != i)
  CRCOMP_C <- CRCOMP
}
CRCOMP_C

```

```{Adding Three Columns of Derived Calculations}
#Subsetting CRCOMP_CI to table with only columns of interest
CRCOMP_CI <- CRCOMP_C[, c(8, 10:16, 18:22)]
view(CRCOMP_CI)

#Adding Enterprise Value column
CRCOMP_CI$EV <- CRCOMP_CI$Preferred.Preference.Stock..Capital....Total + CRCOMP_CI$Long.Term.Debt...Total + CRCOMP_CI$Debt.in.Current.Liabilities...Total + CRCOMP_CI$Preferred.Preference.Stock..Capital....Total - CRCOMP_CI$Cash.and.Short.Term.Investments

#Binding CRCOMP_CI and calculated values
CRCOMP_CIF <- data.frame(Calculated.Market.Capital = (CRCOMP_CI$Common.Shares.Outstanding)*(CRCOMP_CI$Price.Close...Annual...Fiscal),
                          Calculated.Dividend.Yield = (CRCOMP_CI$Dividends.per.Share...Pay.Date...Fiscal)/(CRCOMP_CI$Price.Close...Annual...Fiscal),
                          Calculated.EBITDA.EV = (CRCOMP_CI$Earnings.Before.Interest)/(CRCOMP_CI$EV)) %>% cbind(CRCOMP_CI)
view(CRCOMP_CIF)

```

```{Calculating Coverages}
CRCOMP_CIG <- sapply(CRCOMP_CIF, cov) %>% data.frame()

#Converting row names into the first column of CRCOMP_CIF and Removing periods
Description <- gsub("\\.", " ", rownames(CRCOMP_CIG)) %>% str_squish()
CRCOMP_CIG <- cbind(Description, data.frame(CRCOMP_CIG, row.names = NULL))

colnames(CRCOMP_CIG)[2] <- "Coverage (%)"
view(CRCOMP_CIG)
```


```{Calculating Coverages}
#Replacing characters in Description column
CRCOMP_CIG$Description[c(3, 9, 16:17)] <- c("Calculated EBITDA/EV", "Earnings Before Interest (EBITDA)", "S&P Economic Sector Code", "Enterprise Value (EV)")

view(CRCOMP_CIG)

```

```{Creating Variable Column and Binding it to CRCOMP_CIG}
Variables <- data.frame(Variable = c("MCAP", "DIVY", "EBEV", "TIC", "CHE", "CSHO", "DLC", "DLTT", "EBITDA", "PSTK", "EXCHG", "DVPSPF", "MKVALT", "PRCCF",
                                     "GSECTOR", "SPCSECCD", "EV"))

CRCOMP_FINAL <- cbind(Variables, CRCOMP_CIG)
view(CRCOMP_FINAL)

```

```{Exporting CRCOMP_FINAL Data Frame as a PDF Final}
pdf("CRCOMP_FINAL.pdf", height = 11, width = 8.5)
grid.table(CRCOMP_FINAL)
dev.off()
#Try out new methods of creating a table! 
```

---
Analyzing Market Cap
---

```{Data Wrangling}
CRCOMP_CID <- cbind(CRCOMP_CIF, data.frame(CRCOMP_C$Data.Date, CRCOMP_C$Ticker.Symbol))

colnames(CRCOMP_CID)[18] <- "Date"

CRCOMP_CID <- CRCOMP_CID %>% arrange(Date)

view(CRCOMP_CID)

CRCOMP_CID <- CRCOMP_CID %>% drop_na(Calculated.Market.Capital)

CRCOMP_CID.Calculated.Market.Capital <- data.frame(CRCOMP_CID$Calculated.Market.Capital)

colnames(CRCOMP_CID.Calculated.Market.Capital) <- "MCAP"

head(CRCOMP_CID.Calculated.Market.Capital)

```

```{Observing the Boxplot Distribution}
# Summary Statistics of Market Capitalization Distribution
summary(CRCOMP_CID.Calculated.Market.Capital$MCAP)
#min: 0, Q1: 28.7, Median: 130.8, Mean: 2519.4, Q3: 682.2, Max: 1966078.9 (AAPL)

IQR(CRCOMP_CID.Calculated.Market.Capital$MCAP)
#IGQ = 653.4542

# Plotting Boxplot Distribution
ggplot(data = CRCOMP_CID.Calculated.Market.Capital, aes(y = MCAP)) +
  geom_boxplot() +
  scale_y_log10() +
  labs(x = "Companies in the CCM Database", y = "Market Capitalization ($MM)") +
  ggtitle("Market Capitalization Distribution from 1950 to 2021") +
  theme(axis.ticks.y = element_blank(), axis.text.y = element_blank()) +
  coord_flip()

```

```{Plotting Density Distribution of MCAP Below $1B for 1950-2021}
#Truncate data after $1B based on statistics (IQR)
ggplot(data = subset(CRCOMP_CID.Calculated.Market.Capital, MCAP <= 1000), aes(MCAP)) +
  geom_density()+
  labs(x = "Market Capitalization ($MM)", y = "Density") +
  ggtitle("Market Capitalization Below $1B from 1950 to 2021")

```

```{Plotting Total Market Capitalization (1958-2021)}
# Adding a year column to CRCOMP_CID and calling it CRCOMP_CIY
CRCOMP_CIY <- CRCOMP_CID %>% mutate(Year = format(as.Date(Date), "%Y"))

# Specifying the breaks of the Dates axis as a vector
yearbreaks <- seq(1950, 2020, by = 10)

p <- ggplot(data = aggregate(Calculated.Market.Capital ~ Year, CRCOMP_CIY, sum), aes(x = Year, y = Calculated.Market.Capital)) +
  geom_point() +
  labs(x = "Years 1958-2021", y = "Total Market Capitalization ($MM)") +
  ggtitle("Total Market Capitalization from 1958 to 2021")

p + scale_x_discrete(breaks = yearbreaks)

```

```{Plotting Average Market Capitalization (1958-2021)}
# Defining b (plot variable) - mean is the statistical argument within the aggregate function
b <- ggplot(data = aggregate(Calculated.Market.Capital ~ Year, CRCOMP_CIY, mean), aes(x = Year, y = Calculated.Market.Capital)) +
  geom_point() +
  labs(x = "Years 1958-2021", y = "Average Market Capitalization ($MM)") +
  ggtitle("Average Market Capitalization from 1958 to 2021")

b + scale_x_discrete(breaks = yearbreaks)

```

```{Plotting Different Levels of Market Cap}


```

```{Creating Market Cap Decade Statistics Tables}


```

```{Creating Market Cap Annual Statistics Tables}
## Creating Average MarketCap ##
A <- aggregate(Calculated.Market.Capital ~ Year, CRCOMP_CIY, mean)

AvgMCAP <- select(A, Calculated.Market.Capital)

colnames(AvgMCAP) <- "Average Market Cap Value"

view(AvgMCAP) #Average Market Cap Data Frame

## Year (1958 - 2021) Data Frame ##
Year <- select(A, Year)

View(Year)

## Over Average Data Frame ##
view(CRCOMP_CIY)
Z <- select(CRCOMP_CIY, Calculated.Market.Capital, Year)

## Over Median Data Frame ##


## Over $50M Adjusted Data Frame ##
#Adjust numbers for inflation


```


---
Analyzing Dividend Yield
---

```{r}

```

---
Analyzing EBITDA/EV
---

```{r}

```

---
Creating Tables
---
